### ISSUE TITLE
Graph失败

### ISSUE THREAD

**Issue by qhxb** [quark-engine/quark-rules#7]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/androguard/core/mutf8.py", line 153, in startswith
    return bytes.startswith(self, sub)
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/quark/utils/graph.py", line 21, in wrapper_lookup
    wrapper_lookup(wrapper, next_level_method, native_api)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/quark/utils/graph.py", line 21, in wrapper_lookup
    wrapper_lookup(wrapper, next_level_method, native_api)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/quark/utils/graph.py", line 21, in wrapper_lookup
    wrapper_lookup(wrapper, next_level_method, native_api)
  [Previous line repeated 991 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/quark/utils/graph.py", line 15, in wrapper_lookup
    elif method.is_android_api():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/androguard/core/analysis/analysis.py", line 616, in is_android_api
    if self.method.get_class_name().startswith(candidate):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/androguard/core/mutf8.py", line 155, in startswith
    return bytes.startswith(self, encode(sub))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/androguard/core/mutf8.py", line 64, in encode
    ord_array = [i for i in map(lambda x: ord(x), s)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/androguard/core/mutf8.py", line 64, in <listcomp>
    ord_array = [i for i in map(lambda x: ord(x), s)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/androguard/core/mutf8.py", line 64, in <lambda>
    ord_array = [i for i in map(lambda x: ord(x), s)]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by krnick** [comment]
Hello @qhxb ,

Thank you for reporting this issue, could you kindly provide the APK you used for us to reproduce this problem.

**Comment by qhxb** [comment]
> Hello @qhxb ,
> 
> Thank you for reporting this issue, could you provide the APK you used for us to reproduce this problem.

https://app.mi.com/details?id=com.kwai.videoeditor
我换了这个app还是一样的问题，是不是我环境的问题？
Python 3.8.5
graphviz==0.16
androguard==3.4.0a1

**Comment by qhxb** [comment]
quark-engine==21.3.3
